trigger: 
  branches:
    include:
    - main
    - dev
  paths:
    exclude:
    - '*.yml'

variables:
  vmImageName: 'windows-latest'
  bdxc.version: '4.0.0'

stages:
  - stage: Build
    displayName: Build stage
  
    jobs:  
    - job: Build
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: Assembly-Info-NetCore@2
        inputs:
          Path: '$(Build.SourcesDirectory)'
          FileNames: '**/*.csproj'
          InsertAttributes: false
          FileEncoding: 'auto'
          WriteBOM: false
          VersionNumber: '$(bdxc.version).$(Build.BuildID)'
          FileVersionNumber: '$(bdxc.version).$(Build.BuildID)'
          InformationalVersion: '$(bdxc.version).$(Build.BuildID)'
          PackageVersion: '$(bdxc.version).$(Build.BuildID)'
          LogLevel: 'verbose'
          FailOnWarning: false
          DisableTelemetry: false
          
      - task: DotNetCoreCLI@2
        displayName: 'Restore pa—Åkages'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Build projects'
        inputs:
          command: 'build'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Publish projects'
        inputs:
          command: publish
          publishWebProjects: False
          projects: '**/*.csproj'
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: True

      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifacts'
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
          artifactName: 'drop'
